### ISSUE TITLE
Capstone project Kanban board

### ISSUE THREAD

**Issue by chiztechnology** [HunterX-7/JS-Capstone-project#22]
### Link to the project

Please find below the link to our team project 🔗 
[Github Project](https://github.com/HunterX-7/JS-Capstone-project/projects/1).

## Members 👥 
In our team, we have 3 members: 

1. @rashedarman,
2. @HunterX-7    and 
3. @chiztechnology

**Comment by sumairq** [comment]
### Hi Team, 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Kanban board is ready.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
